/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant_management_system;
import customPackages.RoundedButton;

import java.awt.Color;
import java.awt.Dimension;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ravin
 */
public class FoodMenu extends javax.swing.JFrame {
    Connection dbConnection;
    Statement dbStatement;
    
    String query;

    /**
     * Creates new form FoodMenu
     */
    public FoodMenu() {
        initComponents();
        load_data("");
        load_categories();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAllCategories = new customPackages.RoundedButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCategory = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFoodItems = new javax.swing.JTable();
        btnBack = new customPackages.RoundedButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Food Menu");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 153));
        jLabel6.setText("Categories");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Food Menu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btnAllCategories.setText("All");
        btnAllCategories.setBorderColor(new java.awt.Color(255, 255, 255));
        btnAllCategories.setColor(new java.awt.Color(255, 204, 0));
        btnAllCategories.setColorClick(new java.awt.Color(230, 184, 0));
        btnAllCategories.setColorOver(new java.awt.Color(255, 219, 77));
        btnAllCategories.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAllCategories.setRadius(20);
        btnAllCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAllCategoriesMouseClicked(evt);
            }
        });
        getContentPane().add(btnAllCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, -1));

        pnlCategory.setOpaque(false);
        pnlCategory.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jScrollPane1.setViewportView(pnlCategory);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 740, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 153));
        jLabel5.setText("Food Items");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        tblFoodItems.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        tblFoodItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Price"
            }
        ));
        tblFoodItems.setOpaque(false);
        tblFoodItems.setSelectionBackground(new java.awt.Color(255, 204, 0));
        tblFoodItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFoodItemsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFoodItems);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 740, 450));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-button 32.png"))); // NOI18N
        btnBack.setBorderColor(new java.awt.Color(0, 0, 0));
        btnBack.setColor(new java.awt.Color(255, 204, 0));
        btnBack.setColorClick(new java.awt.Color(230, 184, 0));
        btnBack.setColorOver(new java.awt.Color(255, 219, 77));
        btnBack.setRadius(50);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CashierBackground.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -15, 790, 840));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAllCategoriesMouseClicked
        DefaultTableModel item_table_Model = (DefaultTableModel)tblFoodItems.getModel();
        item_table_Model.setRowCount(0);
        load_data("");
    }//GEN-LAST:event_btnAllCategoriesMouseClicked

    private void tblFoodItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFoodItemsMouseClicked

    }//GEN-LAST:event_tblFoodItemsMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked

        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_btnBackMouseClicked

        public void load_categories(){
        try {
            query = "SELECT DISTINCT category_name FROM categories;";
            ResultSet db_resultSet = dbStatement.executeQuery(query);
                   
            while (db_resultSet.next()) {
                String category = db_resultSet.getString("category_name");
                
                RoundedButton cat_button = new RoundedButton();
                
                cat_button.setRadius(20);
                cat_button.setPreferredSize(new Dimension(80,45));
                cat_button.setColor(new java.awt.Color(255,204,0)); 
                cat_button.setBorderColor(Color.white);
                cat_button.setColorClick(new java.awt.Color(230,184,0));
                cat_button.setColorOver(new java.awt.Color(255,219,77));
                cat_button.setText(category);
                cat_button.getText();
                cat_button.addActionListener(new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        DefaultTableModel item_table_Model = (DefaultTableModel)tblFoodItems.getModel();
                        item_table_Model.setRowCount(0);
                        load_data(cat_button.getText());
                        
                    }
                });       
                pnlCategory.add(cat_button);
            }
        } catch (SQLException sQLException) {
            System.out.println(sQLException);
        }
        
    }
        
            public void load_data(String seleted_category){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            dbConnection = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant_management_system_db","root","");
            dbStatement = dbConnection.createStatement();
            
            if(seleted_category!=""){
                query = "SELECT * FROM food_items WHERE Category='"+seleted_category+"'";
            }else{
                query = "SELECT * FROM food_items;";
            }

            ResultSet db_resultSet = dbStatement.executeQuery(query);
            
            while (db_resultSet.next()){
                String id = String.valueOf(db_resultSet.getInt("ID"));
                String food_name = db_resultSet.getString("Name");
                String category = db_resultSet.getString("Category");
                String price = db_resultSet.getString("Price");
                
                String tbl_Data[]= {id,food_name,category,price};
                DefaultTableModel item_table_Model = (DefaultTableModel)tblFoodItems.getModel();
                item_table_Model.addRow(tbl_Data);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CashierScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CashierScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customPackages.RoundedButton btnAllCategories;
    private customPackages.RoundedButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlCategory;
    private javax.swing.JTable tblFoodItems;
    // End of variables declaration//GEN-END:variables
}
