/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant_management_system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author ravin
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        current_date();
        current_time();
    }

    public final void current_date(){
        Date date = new Date();
        SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy");
        lblDate.setText(date_format.format(date));
    }
    Timer timer;
    SimpleDateFormat time_format = new SimpleDateFormat("hh:mm:ss a");
       
    public final void current_time(){
        timer = new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Date time = new Date();
                lblTime.setText(time_format.format(time));
            }
        });
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManager = new customPackages.RoundedButton();
        btnMenu = new customPackages.RoundedButton();
        btnCashier = new customPackages.RoundedButton();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Food Corner");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManager.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\images\\Manager.png"));
        btnManager.setText("Manager");
        btnManager.setBorderColor(new java.awt.Color(255, 255, 255));
        btnManager.setColor(new java.awt.Color(255, 153, 0));
        btnManager.setColorClick(new java.awt.Color(204, 153, 0));
        btnManager.setColorOver(new java.awt.Color(255, 204, 51));
        btnManager.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnManager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManager.setRadius(25);
        btnManager.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManagerMouseClicked(evt);
            }
        });
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 130, 130));

        btnMenu.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\images\\menu.png"));
        btnMenu.setText("Menu");
        btnMenu.setBorderColor(new java.awt.Color(255, 255, 255));
        btnMenu.setColor(new java.awt.Color(255, 153, 0));
        btnMenu.setColorClick(new java.awt.Color(204, 153, 0));
        btnMenu.setColorOver(new java.awt.Color(255, 204, 51));
        btnMenu.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu.setRadius(25);
        btnMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 130, 130));

        btnCashier.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\images\\Cashier.png"));
        btnCashier.setText("Cashier");
        btnCashier.setBorderColor(new java.awt.Color(255, 255, 255));
        btnCashier.setColor(new java.awt.Color(255, 153, 0));
        btnCashier.setColorClick(new java.awt.Color(204, 153, 0));
        btnCashier.setColorOver(new java.awt.Color(255, 204, 51));
        btnCashier.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCashier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCashier.setRadius(25);
        btnCashier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCashierMouseClicked(evt);
            }
        });
        btnCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierActionPerformed(evt);
            }
        });
        getContentPane().add(btnCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 130, 130));

        lblDate.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("12/11/2022");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, -1, -1));

        lblTime.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("11:48:00 AM");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, -1, -1));

        lblTitle.setFont(new java.awt.Font("Fredericka the Great", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("FOOD CORNER");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblTitle1.setFont(new java.awt.Font("Fredericka the Great", 1, 37)); // NOI18N
        lblTitle1.setText("FOOD CORNER");
        getContentPane().add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 101, -1, -1));

        imgBackground.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\images\\MainBackground.jpg"));
        imgBackground.setText("jLabel1");
        imgBackground.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagerActionPerformed

    private void btnCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCashierActionPerformed

    private void btnCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCashierMouseClicked
        LoginScreen_Cashier cashierLogin = new LoginScreen_Cashier();
        cashierLogin.setVisible(true);
        
    }//GEN-LAST:event_btnCashierMouseClicked

    private void btnManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagerMouseClicked
       LoginScreen_Manager managerLogin = new LoginScreen_Manager();
       managerLogin.setVisible(true);
    }//GEN-LAST:event_btnManagerMouseClicked

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
       FoodMenu foodmenu = new FoodMenu();
       foodmenu.setVisible(true);
    }//GEN-LAST:event_btnMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customPackages.RoundedButton btnCashier;
    private customPackages.RoundedButton btnManager;
    private customPackages.RoundedButton btnMenu;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
