/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant_management_system;

import customPackages.RoundedButton;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ravin
 */
public class ManagerScreen extends javax.swing.JFrame {
    Date date = new Date();
    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy");
    
    Timer timer;
    SimpleDateFormat time_format = new SimpleDateFormat("hh:mm:ss a");
    
    Connection dbConnection;
    Statement dbStatement;
    PreparedStatement dbPrepareStatement;
    String query;
    int current_food_ID=0;
    int selected_row_id=0;
    String position="Cashier";
    String gender="Male";
    int selected_userID=0;
    
    /**
     * Creates new form ManagerScreen
     */
    public ManagerScreen() {
        initComponents();
        load_FoodData("");
        load_UserData("");
        load_categories();
        load_current_Food_ID();
        load_current_user_ID();
        load_DailySalesData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpPositions = new javax.swing.ButtonGroup();
        btnGrpGender = new javax.swing.ButtonGroup();
        tbpnlManager = new javax.swing.JTabbedPane();
        pnlFoodItems = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFoodID = new javax.swing.JTextField();
        txtFoodName = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        txtFoodPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFoodItems = new javax.swing.JTable();
        btnFoodAdd = new customPackages.RoundedButton();
        btnFoodUpdate = new customPackages.RoundedButton();
        btnFoodDelete = new customPackages.RoundedButton();
        btnFoodReset = new customPackages.RoundedButton();
        jLabel16 = new javax.swing.JLabel();
        pnlUsers = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        btnUserAdd = new customPackages.RoundedButton();
        btnUserUpdate = new customPackages.RoundedButton();
        btnUserDelete = new customPackages.RoundedButton();
        btnUserReset = new customPackages.RoundedButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUserTable = new javax.swing.JTable();
        rbtnCashier = new javax.swing.JRadioButton();
        rbtnManager = new javax.swing.JRadioButton();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        pnlReports = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnPrintDailyReport = new customPackages.RoundedButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDailySales = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        lblDailyReportTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFoodItemsReport = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        cmbCategoryReport = new javax.swing.JComboBox<>();
        btnFoodSearchReport = new customPackages.RoundedButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblUserTableReport = new javax.swing.JTable();
        cmbUserPositionReport = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        btnUserSearchReport = new customPackages.RoundedButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        cmbReportMonth = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblReportSubtotal = new javax.swing.JLabel();
        btnSalesSearchReport = new customPackages.RoundedButton();
        btnPrintMonthlyReport = new customPackages.RoundedButton();
        lblTitle = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        btnBack = new customPackages.RoundedButton();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFoodItems.setBackground(new java.awt.Color(255, 255, 255));
        pnlFoodItems.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("Food Name");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setText("Category");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel4.setText("Price");

        tblFoodItems.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblFoodItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Food Name", "Category", "Price"
            }
        ));
        tblFoodItems.setGridColor(new java.awt.Color(255, 255, 51));
        tblFoodItems.setSelectionBackground(new java.awt.Color(255, 204, 0));
        tblFoodItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFoodItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFoodItems);

        btnFoodAdd.setText("Add");
        btnFoodAdd.setMaximumSize(new java.awt.Dimension(70, 30));
        btnFoodAdd.setMinimumSize(new java.awt.Dimension(70, 30));
        btnFoodAdd.setPreferredSize(new java.awt.Dimension(70, 30));
        btnFoodAdd.setRadius(20);
        btnFoodAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFoodAddMouseClicked(evt);
            }
        });

        btnFoodUpdate.setText("Update");
        btnFoodUpdate.setMaximumSize(new java.awt.Dimension(70, 30));
        btnFoodUpdate.setMinimumSize(new java.awt.Dimension(70, 30));
        btnFoodUpdate.setPreferredSize(new java.awt.Dimension(70, 30));
        btnFoodUpdate.setRadius(20);
        btnFoodUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFoodUpdateMouseClicked(evt);
            }
        });

        btnFoodDelete.setText("Delete");
        btnFoodDelete.setMaximumSize(new java.awt.Dimension(70, 30));
        btnFoodDelete.setMinimumSize(new java.awt.Dimension(70, 30));
        btnFoodDelete.setPreferredSize(new java.awt.Dimension(70, 30));
        btnFoodDelete.setRadius(20);
        btnFoodDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFoodDeleteMouseClicked(evt);
            }
        });

        btnFoodReset.setText("Reset");
        btnFoodReset.setMaximumSize(new java.awt.Dimension(70, 30));
        btnFoodReset.setMinimumSize(new java.awt.Dimension(70, 30));
        btnFoodReset.setPreferredSize(new java.awt.Dimension(70, 30));
        btnFoodReset.setRadius(20);
        btnFoodReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFoodResetMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel16.setText("Food Items");

        javax.swing.GroupLayout pnlFoodItemsLayout = new javax.swing.GroupLayout(pnlFoodItems);
        pnlFoodItems.setLayout(pnlFoodItemsLayout);
        pnlFoodItemsLayout.setHorizontalGroup(
            pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFoodItemsLayout.createSequentialGroup()
                .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFoodItemsLayout.createSequentialGroup()
                        .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFoodItemsLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFoodAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFoodDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFoodReset, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFoodUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 70, Short.MAX_VALUE))
                            .addGroup(pnlFoodItemsLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addGap(25, 25, 25)
                                .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFoodPrice)
                                    .addComponent(txtFoodName)
                                    .addGroup(pnlFoodItemsLayout.createSequentialGroup()
                                        .addComponent(txtFoodID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(37, 37, 37))
                    .addGroup(pnlFoodItemsLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlFoodItemsLayout.setVerticalGroup(
            pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFoodItemsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFoodItemsLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFoodID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFoodAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFoodUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFoodItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFoodDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFoodReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        tbpnlManager.addTab("Food Items", pnlFoodItems);

        pnlUsers.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsers.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setText("User ID");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setText("User Name");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel7.setText("Position");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel9.setText("Address");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel10.setText("Telephone");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel11.setText("Gender");

        btnUserAdd.setText("Add");
        btnUserAdd.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnUserAdd.setRadius(20);
        btnUserAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserAddMouseClicked(evt);
            }
        });

        btnUserUpdate.setText("Update");
        btnUserUpdate.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnUserUpdate.setRadius(20);
        btnUserUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserUpdateMouseClicked(evt);
            }
        });

        btnUserDelete.setText("Delete");
        btnUserDelete.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnUserDelete.setRadius(20);
        btnUserDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserDeleteMouseClicked(evt);
            }
        });

        btnUserReset.setText("Reset");
        btnUserReset.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnUserReset.setRadius(20);
        btnUserReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserResetMouseClicked(evt);
            }
        });

        tblUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "User Name", "Position", "Password", "Address", "Telephone", "Gender"
            }
        ));
        tblUserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUserTable);

        btnGrpPositions.add(rbtnCashier);
        rbtnCashier.setSelected(true);
        rbtnCashier.setText("Cashier");
        rbtnCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnCashierMouseClicked(evt);
            }
        });

        btnGrpPositions.add(rbtnManager);
        rbtnManager.setText("Manager");
        rbtnManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnManagerMouseClicked(evt);
            }
        });

        btnGrpGender.add(rbtnMale);
        rbtnMale.setSelected(true);
        rbtnMale.setText("Male");
        rbtnMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnMaleMouseClicked(evt);
            }
        });

        btnGrpGender.add(rbtnFemale);
        rbtnFemale.setText("Female");
        rbtnFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnFemaleMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel17.setText("Users");

        javax.swing.GroupLayout pnlUsersLayout = new javax.swing.GroupLayout(pnlUsers);
        pnlUsers.setLayout(pnlUsersLayout);
        pnlUsersLayout.setHorizontalGroup(
            pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsersLayout.createSequentialGroup()
                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsersLayout.createSequentialGroup()
                        .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUsersLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUserName)
                                    .addGroup(pnlUsersLayout.createSequentialGroup()
                                        .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pnlUsersLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnUserDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUserUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUserReset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlUsersLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddress)
                                    .addGroup(pnlUsersLayout.createSequentialGroup()
                                        .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 15, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18))
                    .addGroup(pnlUsersLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUsersLayout.createSequentialGroup()
                                .addComponent(rbtnCashier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnManager))
                            .addGroup(pnlUsersLayout.createSequentialGroup()
                                .addComponent(rbtnMale)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnFemale)))
                        .addGap(46, 46, 46))
                    .addGroup(pnlUsersLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlUsersLayout.setVerticalGroup(
            pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsersLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(63, 63, 63))
            .addGroup(pnlUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnCashier)
                    .addComponent(rbtnManager))
                .addGap(15, 15, 15)
                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsersLayout.createSequentialGroup()
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(pnlUsersLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMale)
                    .addComponent(rbtnFemale)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUserAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUserDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        tbpnlManager.addTab("Users", pnlUsers);

        pnlReports.setBackground(new java.awt.Color(255, 255, 255));
        pnlReports.setOpaque(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);

        btnPrintDailyReport.setBackground(new java.awt.Color(255, 204, 0));
        btnPrintDailyReport.setText("Print");
        btnPrintDailyReport.setBorderColor(new java.awt.Color(0, 0, 0));
        btnPrintDailyReport.setColor(new java.awt.Color(255, 204, 0));
        btnPrintDailyReport.setColorClick(new java.awt.Color(230, 184, 0));
        btnPrintDailyReport.setColorOver(new java.awt.Color(255, 219, 77));
        btnPrintDailyReport.setRadius(20);

        tblDailySales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Time", "Number Of Items", "Sub Total"
            }
        ));
        jScrollPane6.setViewportView(tblDailySales);

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel18.setText("Total value Of Sales : Rs.");

        lblDailyReportTotal.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblDailyReportTotal.setText("00.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDailyReportTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrintDailyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDailyReportTotal))
                    .addComponent(btnPrintDailyReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Daily Sales Report", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        tblFoodItemsReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Food Name", "Category", "Price"
            }
        ));
        tblFoodItemsReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFoodItemsReportMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblFoodItemsReport);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel14.setText("Category");

        cmbCategoryReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        btnFoodSearchReport.setText("Search");
        btnFoodSearchReport.setBorderColor(new java.awt.Color(0, 0, 0));
        btnFoodSearchReport.setColor(new java.awt.Color(255, 204, 0));
        btnFoodSearchReport.setColorClick(new java.awt.Color(230, 184, 0));
        btnFoodSearchReport.setColorOver(new java.awt.Color(255, 219, 77));
        btnFoodSearchReport.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnFoodSearchReport.setRadius(20);
        btnFoodSearchReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFoodSearchReportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCategoryReport, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFoodSearchReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoryReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(btnFoodSearchReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Food Report", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        tblUserTableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "User Name", "Position", "Password", "Address", "Telephone", "Gender"
            }
        ));
        tblUserTableReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserTableReportMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblUserTableReport);

        cmbUserPositionReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Manager", "Cashier", " " }));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel13.setText("Position");

        btnUserSearchReport.setText("Search");
        btnUserSearchReport.setBorderColor(new java.awt.Color(0, 0, 0));
        btnUserSearchReport.setColor(new java.awt.Color(255, 204, 0));
        btnUserSearchReport.setColorClick(new java.awt.Color(230, 184, 0));
        btnUserSearchReport.setColorOver(new java.awt.Color(255, 219, 77));
        btnUserSearchReport.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnUserSearchReport.setRadius(20);
        btnUserSearchReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserSearchReportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbUserPositionReport, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUserSearchReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbUserPositionReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserSearchReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Users Report", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);

        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Time", "Number Of Items", "Sub Total"
            }
        ));
        jScrollPane3.setViewportView(tblSales);

        cmbReportMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " " }));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel12.setText("Month");

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel15.setText("Total value Of Sales : Rs.");

        lblReportSubtotal.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblReportSubtotal.setText("00.00");

        btnSalesSearchReport.setText("Search");
        btnSalesSearchReport.setBorderColor(new java.awt.Color(0, 0, 0));
        btnSalesSearchReport.setColor(new java.awt.Color(255, 204, 0));
        btnSalesSearchReport.setColorClick(new java.awt.Color(230, 184, 0));
        btnSalesSearchReport.setColorOver(new java.awt.Color(255, 219, 77));
        btnSalesSearchReport.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        btnSalesSearchReport.setRadius(20);
        btnSalesSearchReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalesSearchReportMouseClicked(evt);
            }
        });

        btnPrintMonthlyReport.setBackground(new java.awt.Color(255, 204, 0));
        btnPrintMonthlyReport.setText("Print");
        btnPrintMonthlyReport.setBorderColor(new java.awt.Color(0, 0, 0));
        btnPrintMonthlyReport.setColor(new java.awt.Color(255, 204, 0));
        btnPrintMonthlyReport.setColorClick(new java.awt.Color(230, 184, 0));
        btnPrintMonthlyReport.setColorOver(new java.awt.Color(255, 219, 77));
        btnPrintMonthlyReport.setRadius(20);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbReportMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalesSearchReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrintMonthlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblReportSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReportSubtotal)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalesSearchReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbReportMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrintMonthlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Monthly Sales Report", jPanel3);

        javax.swing.GroupLayout pnlReportsLayout = new javax.swing.GroupLayout(pnlReports);
        pnlReports.setLayout(pnlReportsLayout);
        pnlReportsLayout.setHorizontalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        pnlReportsLayout.setVerticalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        tbpnlManager.addTab("Reports", pnlReports);

        getContentPane().add(tbpnlManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 930, 480));

        lblTitle.setFont(new java.awt.Font("Fredericka the Great", 0, 34)); // NOI18N
        lblTitle.setText("FOOD CORNER");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUserName.setText("Manager");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\images\\back-button 32.png"));
        btnBack.setBorderColor(new java.awt.Color(0, 0, 0));
        btnBack.setColor(new java.awt.Color(255, 204, 0));
        btnBack.setColorClick(new java.awt.Color(230, 184, 0));
        btnBack.setColorOver(new java.awt.Color(255, 219, 77));
        btnBack.setRadius(50);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 7, 45, 45));

        imgBackground.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\images\\ManagerBackground.jpg"));
        imgBackground.setText("jLabel1");
        getContentPane().add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFoodAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodAddMouseClicked
        try {
            query = "INSERT INTO food_items values(?,?,?,?)";
            dbPrepareStatement = dbConnection.prepareStatement(query);
            dbPrepareStatement.setInt(1,Integer.parseInt(txtFoodID.getText()));
            dbPrepareStatement.setString(2,txtFoodName.getText());
            dbPrepareStatement.setString(3,cmbCategory.getItemAt(cmbCategory.getSelectedIndex()));
            dbPrepareStatement.setDouble(4,Double.parseDouble(txtFoodPrice.getText()));
            int result_set=dbPrepareStatement.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data added successfully","Inserting info",JOptionPane.INFORMATION_MESSAGE);
            dbPrepareStatement.close();
            
            DefaultTableModel item_table_Model = (DefaultTableModel)tblFoodItems.getModel();
            item_table_Model.setRowCount(0);
            load_FoodData("");
            resetInputs();
            
        } catch (SQLException sQLException) {
            System.out.println(sQLException);
        }
    }//GEN-LAST:event_btnFoodAddMouseClicked

    private void tblFoodItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFoodItemsMouseClicked
        DefaultTableModel item_table_Model = (DefaultTableModel) tblFoodItems.getModel(); 
        selected_row_id = Integer.parseInt(item_table_Model.getValueAt(tblFoodItems.getSelectedRow(), 0).toString());

        txtFoodID.setText(item_table_Model.getValueAt(tblFoodItems.getSelectedRow(), 0).toString());
        txtFoodName.setText(item_table_Model.getValueAt(tblFoodItems.getSelectedRow(), 1).toString());
        cmbCategory.setSelectedItem((item_table_Model.getValueAt(tblFoodItems.getSelectedRow(), 2).toString()));
        txtFoodPrice.setText(item_table_Model.getValueAt(tblFoodItems.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tblFoodItemsMouseClicked

    private void btnFoodUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodUpdateMouseClicked
        try {
            query = "UPDATE food_items set ID=?,Name=?,Category=?,Price=? WHERE ID='"+selected_row_id+"'";
            dbPrepareStatement = dbConnection.prepareStatement(query);
            dbPrepareStatement.setInt(1,Integer.parseInt(txtFoodID.getText()));
            dbPrepareStatement.setString(2,txtFoodName.getText());
            dbPrepareStatement.setString(3,cmbCategory.getItemAt(cmbCategory.getSelectedIndex()));
            dbPrepareStatement.setDouble(4,Double.parseDouble(txtFoodPrice.getText()));
            int result_set=dbPrepareStatement.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data Updated successfully","Update info",JOptionPane.INFORMATION_MESSAGE);
            dbPrepareStatement.close();
            
            DefaultTableModel item_table_Model = (DefaultTableModel)tblFoodItems.getModel();
            item_table_Model.setRowCount(0);
            load_FoodData("");
            resetInputs();
            
        } catch (SQLException sQLException) {
            System.out.println(sQLException);
        }     
    }//GEN-LAST:event_btnFoodUpdateMouseClicked

    private void btnFoodDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodDeleteMouseClicked
        try {
            query = "DELETE FROM food_items WHERE ID='"+selected_row_id+"'";

            int result_set=dbStatement.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"data added successfully","data insertion",JOptionPane.INFORMATION_MESSAGE);
            

            load_FoodData("");
            resetInputs();
            
        } catch (SQLException sQLException) {
            System.out.println(sQLException);
        }  
    }//GEN-LAST:event_btnFoodDeleteMouseClicked

    private void btnFoodResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodResetMouseClicked
        load_current_Food_ID();
        resetInputs();
    }//GEN-LAST:event_btnFoodResetMouseClicked

    private void btnUserAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserAddMouseClicked
        
        try {
            query = "INSERT INTO users VALUES(?,?,?,?,?,?,?)";
            dbPrepareStatement = dbConnection.prepareStatement(query);
            
            dbPrepareStatement.setInt(1,Integer.parseInt(txtUserID.getText()));
            dbPrepareStatement.setString(2, txtUserName.getText());
            dbPrepareStatement.setString(3 , position);
            dbPrepareStatement.setInt(4 ,Integer.parseInt(txtPassword.getText()));
            dbPrepareStatement.setString(5 , txtAddress.getText());
            dbPrepareStatement.setInt(6 ,Integer.parseInt(txtTelephone.getText()));
            dbPrepareStatement.setString(7 , gender);
            
            int result_Set = dbPrepareStatement.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data added successfully","Data Insertion",JOptionPane.INFORMATION_MESSAGE);
            dbPrepareStatement.close();
            
            load_UserData("");
            
        } catch (SQLException sQLException) {
            System.out.println(sQLException);
        }
    }//GEN-LAST:event_btnUserAddMouseClicked

    private void rbtnManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnManagerMouseClicked

            position = "Manager";
    }//GEN-LAST:event_rbtnManagerMouseClicked

    private void rbtnCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnCashierMouseClicked

            position = "Cashier";
    }//GEN-LAST:event_rbtnCashierMouseClicked

    private void rbtnMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnMaleMouseClicked

            gender = "Male";
    }//GEN-LAST:event_rbtnMaleMouseClicked

    private void rbtnFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnFemaleMouseClicked

            gender = "Female";
    }//GEN-LAST:event_rbtnFemaleMouseClicked

    private void btnUserUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserUpdateMouseClicked
                                   
        try {
            query = "UPDATE users SET UserName=?, Position=?, Password=?, Address=?, Telephone=?, Gender=? WHERE UserID='"+selected_userID+"'";
            dbPrepareStatement = dbConnection.prepareStatement(query);
            
            dbPrepareStatement.setString(2, txtUserName.getText());
            dbPrepareStatement.setString(3 , position);
            dbPrepareStatement.setInt(4 ,Integer.parseInt(txtPassword.getText()));
            dbPrepareStatement.setString(5 , txtAddress.getText());
            dbPrepareStatement.setInt(6 ,Integer.parseInt(txtTelephone.getText()));
            dbPrepareStatement.setString(7 , gender);
            
            int result_Set = dbPrepareStatement.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data updated successfully","Data Updation",JOptionPane.INFORMATION_MESSAGE);
            dbPrepareStatement.close();
            
            load_UserData("");
            
        } catch (SQLException sQLException) {
        }
    }//GEN-LAST:event_btnUserUpdateMouseClicked

    private void tblUserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserTableMouseClicked
        DefaultTableModel users_table_Model = (DefaultTableModel) tblUserTable.getModel();
        selected_userID = Integer.parseInt(users_table_Model.getValueAt(tblUserTable.getSelectedRow(), 0).toString());
        txtUserID.setText(users_table_Model.getValueAt(tblUserTable.getSelectedRow(), 0).toString());
        txtUserName.setText(users_table_Model.getValueAt(tblUserTable.getSelectedRow(), 1).toString());
        txtPassword.setText(users_table_Model.getValueAt(tblUserTable.getSelectedRow(), 3).toString());
        txtAddress.setText(users_table_Model.getValueAt(tblUserTable.getSelectedRow(), 4).toString());
        txtTelephone.setText(users_table_Model.getValueAt(tblUserTable.getSelectedRow(), 5).toString());
        
        if(users_table_Model.getValueAt(tblUserTable.getSelectedRow(), 6).toString()=="Male"){
             rbtnMale.setSelected(true);
        }else{
             rbtnFemale.setSelected(false);
        }
    }//GEN-LAST:event_tblUserTableMouseClicked

    private void btnUserDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserDeleteMouseClicked
        try {
            query = "DELETE FROM users WHERE UserID = '"+selected_userID+"'";
            
            int result_Set = dbStatement.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"Data deleted successfully","Delete Info",JOptionPane.INFORMATION_MESSAGE);
            

            load_UserData("");
            } catch (SQLException sQLException) {
                System.out.println(sQLException);
        }   
    }//GEN-LAST:event_btnUserDeleteMouseClicked

    private void btnUserResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserResetMouseClicked
        txtUserID.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        txtAddress.setText("");
        txtTelephone.setText("");
        load_UserData("");
        load_current_user_ID();
    }//GEN-LAST:event_btnUserResetMouseClicked

    private void tblFoodItemsReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFoodItemsReportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblFoodItemsReportMouseClicked

    private void tblUserTableReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserTableReportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUserTableReportMouseClicked

    private void btnFoodSearchReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFoodSearchReportMouseClicked

        load_FoodData(cmbCategoryReport.getItemAt(cmbCategoryReport.getSelectedIndex()));
    }//GEN-LAST:event_btnFoodSearchReportMouseClicked

    private void btnUserSearchReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserSearchReportMouseClicked

        load_UserData(cmbUserPositionReport.getItemAt(cmbUserPositionReport.getSelectedIndex()));
    }//GEN-LAST:event_btnUserSearchReportMouseClicked

    private void btnSalesSearchReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalesSearchReportMouseClicked
        load_SalesData(cmbUserPositionReport.getSelectedIndex());
    }//GEN-LAST:event_btnSalesSearchReportMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    public void load_FoodData(String seleted_category){
                          
        DefaultTableModel item_table_Model = (DefaultTableModel)tblFoodItems.getModel();
        item_table_Model.setRowCount(0);
        
        DefaultTableModel item_Report_table_Model = (DefaultTableModel)tblFoodItemsReport.getModel();
        item_Report_table_Model.setRowCount(0);
        try {
           Class.forName("com.mysql.cj.jdbc.Driver");
            dbConnection = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant_management_system_db","root","");
            dbStatement = dbConnection.createStatement();
            
            if(seleted_category=="All" || seleted_category==""){
                query = "SELECT * FROM food_items;";
            }else if(seleted_category!=""){
                query = "SELECT * FROM food_items WHERE Category='"+seleted_category+"'";
            }

            ResultSet db_resultSet = dbStatement.executeQuery(query);
            
            while (db_resultSet.next()){
                String id = String.valueOf(db_resultSet.getInt("ID"));
                String food_name = db_resultSet.getString("Name");
                String category = db_resultSet.getString("Category");
                String price = db_resultSet.getString("Price");
                
                String tbl_Data[]= {id,food_name,category,price};

                item_table_Model.addRow(tbl_Data);
                item_Report_table_Model.addRow(tbl_Data);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CashierScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CashierScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void load_UserData(String selected_Position){
        DefaultTableModel report_item_table_Model = (DefaultTableModel)tblUserTableReport.getModel();
        report_item_table_Model.setRowCount(0);
        
        DefaultTableModel user_table_Model = (DefaultTableModel)tblUserTable.getModel();
        user_table_Model.setRowCount(0);
        
        try {
            if(selected_Position=="All" || selected_Position==""){
                query = "SELECT * FROM users;";
            }else if(selected_Position!=""){
                query = "SELECT * FROM users WHERE position='"+selected_Position+"';";
            }
            
            
            ResultSet db_resultSet = dbStatement.executeQuery(query);
            while (db_resultSet.next()){
                String userID = String.valueOf(db_resultSet.getInt("UserID"));
                String userName = db_resultSet.getString("UserName");
                String position = db_resultSet.getString("Position");
                String password = db_resultSet.getString("Password");
                String address = db_resultSet.getString("Address");
                String telephone = db_resultSet.getString("Telephone");
                String gender = db_resultSet.getString("Gender");
                
                String tbl_Data[] = {userID, userName, position, password, address, telephone, gender };

                user_table_Model.addRow(tbl_Data);
                report_item_table_Model.addRow(tbl_Data);
                
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
    public void load_SalesData(int selected_month){
        double monthlySubtotal=0.0;
        try {
            if(selected_month==0 ){
                query = "SELECT * FROM bill_details;";
            }else if(selected_month!=0){
                query = "SELECT * FROM bill_details WHERE Date LIKE '"+Integer.toString(selected_month+1)+"';";
            }
            
            
            ResultSet db_resultSet = dbStatement.executeQuery(query);
            while (db_resultSet.next()){
                String salesID = String.valueOf(db_resultSet.getInt("ID"));
                String salesDate = db_resultSet.getString("Date");
                String salesTime = db_resultSet.getString("Time");
                String number_Of_Items = String.valueOf(db_resultSet.getInt("Number_Of_Items"));
                String subTotal = String.valueOf(db_resultSet.getDouble("SubTotal"));
                
                monthlySubtotal = monthlySubtotal + db_resultSet.getDouble("SubTotal");
                
                String tbl_Data[] = {salesID, salesDate, salesTime, number_Of_Items, subTotal };

                DefaultTableModel sales_table_Model = (DefaultTableModel) tblSales.getModel();
                sales_table_Model.addRow(tbl_Data);
                
                lblReportSubtotal.setText(Double.toString(monthlySubtotal));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(CashierScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
        
        public void load_DailySalesData(){
        double dailySubtotal=0.0;
        try {

            Date date = new Date();
            SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
    
            query = "SELECT * FROM bill_details WHERE Date='"+date_format.format(date)+"';";
            
            ResultSet db_resultSet = dbStatement.executeQuery(query);
            while (db_resultSet.next()){
                String salesID = String.valueOf(db_resultSet.getInt("ID"));
                String salesDate = db_resultSet.getString("Date");
                String salesTime = db_resultSet.getString("Time");
                String number_Of_Items = String.valueOf(db_resultSet.getInt("Number_Of_Items"));
                String subTotal = String.valueOf(db_resultSet.getDouble("SubTotal"));
                
                dailySubtotal = dailySubtotal + db_resultSet.getDouble("SubTotal");
                
                String tbl_Data[] = {salesID, salesDate, salesTime, number_Of_Items, subTotal };

                DefaultTableModel sales_table_Model = (DefaultTableModel) tblDailySales.getModel();
                sales_table_Model.addRow(tbl_Data);
                
                lblDailyReportTotal.setText(Double.toString(dailySubtotal));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(CashierScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    public void load_categories(){
        try {
            query = "SELECT DISTINCT category_name FROM categories;";
            ResultSet db_resultSet = dbStatement.executeQuery(query);
                   
            while (db_resultSet.next()) {
                String category = db_resultSet.getString("category_name");
                cmbCategory.addItem(category);
                cmbCategoryReport.addItem(category);
            }
        } catch (SQLException sQLException) {
            System.out.println(sQLException);
        }
        
    }
        
    public void load_current_Food_ID(){
        try {
            query = "SELECT MAX(ID) FROM food_items;";
            ResultSet db_resultSet = dbStatement.executeQuery(query);
            
            while (db_resultSet.next()) {
                txtFoodID.setText(Integer.toString(db_resultSet.getInt("MAX(ID)")+1));
            }   
            
        } catch (SQLException sQLException) {
            System.out.print(sQLException);
        }
    }
    
    public void load_current_user_ID(){
        try {
            query = "SELECT MAX(UserID) FROM users;";
            ResultSet db_resultSet = dbStatement.executeQuery(query);
            
            while (db_resultSet.next()) {
                txtUserID.setText(Integer.toString(db_resultSet.getInt("MAX(UserID)")+1));
            }   
            
        } catch (SQLException sQLException) {
            System.out.print(sQLException);
        }
    }
    
    public void resetInputs(){
        txtFoodID.setText("");
        txtFoodName.setText("");
        txtFoodPrice.setText("");
        load_FoodData("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customPackages.RoundedButton btnBack;
    private customPackages.RoundedButton btnFoodAdd;
    private customPackages.RoundedButton btnFoodDelete;
    private customPackages.RoundedButton btnFoodReset;
    private customPackages.RoundedButton btnFoodSearchReport;
    private customPackages.RoundedButton btnFoodUpdate;
    private javax.swing.ButtonGroup btnGrpGender;
    private javax.swing.ButtonGroup btnGrpPositions;
    private customPackages.RoundedButton btnPrintDailyReport;
    private customPackages.RoundedButton btnPrintMonthlyReport;
    private customPackages.RoundedButton btnSalesSearchReport;
    private customPackages.RoundedButton btnUserAdd;
    private customPackages.RoundedButton btnUserDelete;
    private customPackages.RoundedButton btnUserReset;
    private customPackages.RoundedButton btnUserSearchReport;
    private customPackages.RoundedButton btnUserUpdate;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbCategoryReport;
    private javax.swing.JComboBox<String> cmbReportMonth;
    private javax.swing.JComboBox<String> cmbUserPositionReport;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDailyReportTotal;
    private javax.swing.JLabel lblReportSubtotal;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlFoodItems;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JPanel pnlUsers;
    private javax.swing.JRadioButton rbtnCashier;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JRadioButton rbtnManager;
    private javax.swing.JTable tblDailySales;
    private javax.swing.JTable tblFoodItems;
    private javax.swing.JTable tblFoodItemsReport;
    private javax.swing.JTable tblSales;
    private javax.swing.JTable tblUserTable;
    private javax.swing.JTable tblUserTableReport;
    private javax.swing.JTabbedPane tbpnlManager;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFoodID;
    private javax.swing.JTextField txtFoodName;
    private javax.swing.JTextField txtFoodPrice;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
