/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurant_management_system;


import javax.swing.JOptionPane;

/**
 *
 * @author ravin
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();

    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingStatus = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 350));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingStatus.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        loadingStatus.setText("Loading...");
        getContentPane().add(loadingStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 140, -1));

        loadingValue.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        loadingValue.setText("0 %");
        getContentPane().add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 37, 20));

        loadingBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loadingBar.setPreferredSize(new java.awt.Dimension(146, 6));
        getContentPane().add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 338, 660, 12));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("Restaurant Food Items Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        lblTitle.setFont(new java.awt.Font("Fredericka the Great", 1, 36)); // NOI18N
        lblTitle.setText("FOOD CORNER");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SplashScreen.jpg"))); // NOI18N
        imgBackground.setText("jLabel4");
        imgBackground.setMaximumSize(new java.awt.Dimension(500, 300));
        imgBackground.setMinimumSize(new java.awt.Dimension(500, 300));
        imgBackground.setPreferredSize(new java.awt.Dimension(600, 350));
        getContentPane().add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay witloadingBar look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        SplashScreen spc = new SplashScreen();
        MainScreen mainScreen = new MainScreen();
        spc.setVisible(true);
        
        try {
            for(int i=0; i<100; i++){
                Thread.sleep(20);
                spc.loadingValue.setText(i+"%");
                if(i==10){
                    spc.loadingStatus.setText("Starting modules..");
                }
                if(i==20){
                    spc.loadingStatus.setText("Connecting database..");
                }
                if(i==50){
                    spc.loadingStatus.setText("Database connected!");
                }
                if(i==70){
                    spc.loadingStatus.setText("Loading UI...");
                }
                if(i==80){
                    spc.loadingStatus.setText("Successfull!");
                }
                spc.loadingBar.setValue(i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        mainScreen.setVisible(true);
        spc.setVisible(false);
        spc.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingStatus;
    private javax.swing.JLabel loadingValue;
    // End of variables declaration//GEN-END:variables
}
